### PR TITLE
Added Arduino Nano V3 package/device

### PR DESCRIPTION
**Pull request by oblerion**
Added package and device for arduino nano v3

Package:
Capture d’écran du 2022-06-28 16-41-51

Device:
Capture d’écran du 2022-06-28 16-42-48

##### DATASHEETS / REFERENCES

board mesure https://jpralves.net/post/2016/11/15/arduino.html

##### CHECKLIST

- [x] I have read and followed the library conventions¹.
- [x] For packages, I followed IPC7351C (see details in library conventions).
- [x] For modified elements, I bumped their version number².
- [x] I already used the new library elements in a design and verified their correctness (optional).
- [x] I'm the copyright owner of the added content (i.e. the changes are made by myself, not copied/imported from somewhere else).
- [x] I agree to publish all my changes under the CC0 Public Domain License³, allowing everyone to use and modify the content without any restrictions.

¹ *Library Conventions: https://docs.librepcb.org/#libraryconventions*
² *Minor version bump if only metadata was modified (e.g. "0.1" -> "0.1.1"), major version bump if functional changes were made (e.g. "0.1" -> "0.2")*
³ *CC0 Public Domain License: https://en.wikipedia.org/wiki/CC0*

### CODE REVIEW

**Comment by ubruhin** [comment]
Thanks for the contribution! I have some comments regarding the package:

- The diameter of the four holes seems to be too small
- The outline violates several rules of the [placement layer](https://docs.librepcb.org/#libraryconventions-packages-placement) and [documentation layer](https://docs.librepcb.org/#libraryconventions-packages-documentation) conventions. Please read these conventions again and apply all these rules. The orientation should also be clarified with the placement layer drawing - in this case, I think I'd simply draw the placement outline **including USB connector**, then the orientation is clear.
- Might also be good to make the first pad rectangular instead of round, then the orientation would even be clear without silkscreen.
- I'd remove the text in the center. The `{{VALUE}}` text at the bottom will contain the text "Arduino Nano V3" anyway by default so this text would then be duplicated.
- I'm not sure about adding all the pad texts - so far we never did that. At least they are only on the documentation layer, so not on silkscreen. @dbrgn do you have an opinion about that? Maybe simply moving them to **inside** the package to avoid conflicts with possible other components around the Arduino? Or better remove them completely?

**Comment by oblerion** [comment]
Capture d’écran du 2022-07-31 11-03-27

- [x] The diameter of the four holes seems to be too small
- [x] The outline violates several rules 
- [x] The orientation should also be clarified with the placement layer drawing - in this case, I think I'd simply draw the placement outline including USB connector, then the orientation is clear.
- [x] Might also be good to make the first pad rectangular instead of round, then the orientation would even be clear without silkscreen.
- [x] I'd remove the text in the center. The {{VALUE}} text at the bottom will contain the text "Arduino Nano V3" anyway by default so this text would then be duplicated.
- [x] I'm not sure about adding all the pad texts - so far we never did that. At least they are only on the documentation layer, so not on silkscreen. @dbrgn do you have an opinion about that? Maybe simply moving them to inside the package to avoid conflicts with possible other components around the Arduino? Or better remove them completely?

**Comment by ubruhin** [comment]
Thanks for the update! Just one thing is now worse than before :see_no_evil: The polygons are now on the "Board Outline" layer, which would lead to a huge cutout milled into your board and is thus fatal :wink:

I wonder where the library conventions are not clear about the outline polygons... There should be two outline polygons:
- One on the "Top Placement" layer which will then be used as silkscreen and thus should be helpful for assembly of that device. Typically it's a line *around* (fully outside, e.g. not drawing the whole USB connector) the package. For Arduino Uno, it would be just a single, closed line around the whole Arduino.
- One on the "Top Documentation", containing the whole outline and additional details (e.g. the whole USB connector) about the package. It does *not* appear on the silkscreen but usually it will be exported in an assembly drawing as an additional placement help.

Examples (the lighter polygons are "Top Placement", the darker polygons are "Top Documentation"):

image

image

I hope this helps. As a simplification, I'd also be fine with only a "Top Placement" polygon if that helps - but "Board Outline" is clearly the wrong layer and needs to be changed :)

**Comment by oblerion** [comment]
You ask about outline so i change to outline XD 
i have only understand this not a board, but an part of board.

**Pull request merged**
